//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChigozieNweke_BookStore
{
    public partial class Admin
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlGenres;

        protected global::System.Web.UI.WebControls.DataList dlBooksByGenre;

        protected global::System.Web.UI.WebControls.SqlDataSource sdsGenres;

        protected global::System.Web.UI.WebControls.SqlDataSource sdsBooksByGenre;

        protected global::System.Web.UI.WebControls.GridView gvGenreAdmin;

        protected global::System.Web.UI.WebControls.SqlDataSource sdsGenreAdmin;

        protected global::System.Web.UI.WebControls.TextBox txtNewGenreName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNewGenreName;

        protected global::System.Web.UI.WebControls.TextBox txtNewGenreDescription;

        protected global::System.Web.UI.WebControls.Button btnAddGenre;

        protected global::System.Web.UI.WebControls.Label lblAdminMessage;

        protected global::System.Web.UI.WebControls.GridView gvBooks;

        protected global::System.Web.UI.WebControls.SqlDataSource sdsBooksGrid;

        protected global::System.Web.UI.WebControls.DetailsView dvBookDetails;

        protected global::System.Web.UI.WebControls.SqlDataSource sdsBookDetails;
    }
}
