//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChigozieNweke_BookStore
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.Label lblWelcome;
    }
}
